#include "blackScholesAnalyticEngineStructs.cuh"
typedef unsigned long size_t;
typedef struct payoffStruct payoffStruct;
typedef struct yieldTermStruct yieldTermStruct;
typedef struct blackVolStruct blackVolStruct;
typedef struct blackScholesMertStruct blackScholesMertStruct;
typedef struct optionStruct optionStruct;
typedef struct blackCalcStruct blackCalcStruct;
typedef struct normalDistStruct normalDistStruct;
typedef struct optionInputStruct optionInputStruct;
//!@$^
typedef struct {
	float vol;
	float intDiscountFactor;
	float R;
	float S;
	float P;
	float Q;
	float s;
	float y;
	float z;
	float r;
	float ax;
	float result;
	float deltax;
	float exponent;
	float xn;
	normalDistStruct currCumNormDist;
	float result;
	int optionNum;
	optionInputStruct threadOption;
	payoffStruct currPayoff;
	yieldTermStruct qTS;
	yieldTermStruct rTS;
	blackVolStruct volTS;
	blackScholesMertStruct stochProcess;
	optionStruct currOption;
	float variance;
	float dividendDiscount;
	float riskFreeDiscount;
	float spot;
	float forwardPrice;
	blackCalcStruct blackCalc;
	float resultVal;
}vals;
